name: Update

on:
  workflow_dispatch:
  schedule:
    # Check for updates every half hour between 15:00 UTC and 19:00 UTC on Tuesday through Thursday
    - cron: '0,30 15-19 * * 2-4'
    # Check for updates every hour between 17:00 UTC and 19:00 UTC on Monday and Friday
    - cron: '0 17-19 * * 1,5'
    # Check for updates at 19:00 UTC once every Saturday and Sunday
    - cron: '0 19 * * 6,0'

env:
  COOKIE: 'ATVNqfLH9EAdrZGpzH5KSedbV0mM00ZPuYIvvb8d+YLOu4xPuynh3/8cmhn+bNPsSRyOsjM5eTPbCuDvv4so30O4b85IqYLbxb7St1B2evYAszI0h0YsEqz4b0aDVW69M2NCriV44/HC6wTcVs7gK2GR7qdvvJXfixr9UxUyGBpThUpVLCVSa8i3LMUpvS7CXbWhg1rWmttDRfTENQ63U0rIQ3lJeafoXKWBeXRABby07wBbx0x+Wc2iNcIwaJR9VA=='

jobs:
  check-for-update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # Step 1: Checkout with full history
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # Important for git operations

      # Step 2: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Step 4: Configure Git for automatic commits
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Step 5: Debug - Check files
      - name: Debug - Check repository structure
        run: |
          echo "=== Checking files ==="
          ls -la
          echo "=== XML files ==="
          ls -la xml/ || echo "No xml directory"
          echo "=== Python files ==="
          find . -name "*.py" | head -10

      # Step 6: Run the main script
      - name: Run update check
        run: python -B main.py
        env:
          ENABLE_NOTIFICATION: ${{ vars.ENABLE_NOTIFICATION }}
          NTFY_TOKEN: ${{ secrets.NTFY_TOKEN }}

      # Step 7: Push changes if any
      - name: Push changes
        run: |
          if ! git diff-index --quiet HEAD --; then
            echo "Changes detected, pushing..."
            git push origin main
          else
            echo "No changes to push"
          fi
